### ISSUE TITLE
Metrics about submissions in the queue, throughput, etc

### ISSUE THREAD

**Issue by mgax** [vmck/acs-deploy#26]
We have Grafana in the cluster. Let's make a nice dashboard that shows the number of pending and running vmck jobs.

@gabriel-v, how can we store the dashboard config in this repo and deploy it to the cluster? Is there some volume where we can write it?

**Comment by Jokeswar** [comment]
We got two dashboards `Acs-Submissions` and `Acs-system`. The first one monitors the number of submissions in queue and the number of currently running ones. It also shows the average CPU and RAM usage of submissions and the current CPU and RAM usage of the entire server. The latter just shows the average CPU and RAM usage of  acs-interface and acs-sync-vmck. @mgax

**Comment by Jokeswar** [comment]
Implemented!
