### ISSUE TITLE
Build images on acs-cluster.

### ISSUE THREAD

**Issue by Jokeswar** [vmck/acs-deploy#30]

**Comment by gmuraru** [comment]
@Jokeswar could you add more details to the issue?
Where are currently the images built?

**Comment by Jokeswar** [comment]
@gmuraru what we want is a CI that will build images from [image-builder](https://github.com/vmck/image-builder) using [.drone.yml](https://github.com/vmck/image-builder/blob/master/.drone.yml). We need to set up [drone](https://drone.io/) and link it to `image-builder`. Sadly I do not have an example at hand.
Currently the vm images are built on a server we nicknamed `frantz`. As a result every time we change an image we have to move it from that server to ours, so `acs-interface` can use it. [Here](https://jenkins.liquiddemo.org/vmck/image-builder/) is where you can see the images being built.

**Comment by gmuraru** [comment]
This is done. The drone link can be accessed from [here](http://frisbee.vmchecker.cs.pub.ro/)
