### ISSUE TITLE
Drone automation

### ISSUE THREAD

**Issue by Jokeswar** [vmck/acs-deploy#35]
Use [DRONE_USER_CREATE](https://docs.drone.io/server/reference/drone-user-create/) to create an admin user with a known token that will set up drone for us. When drone shuts down it looses all the configurations.

**Comment by gmuraru** [comment]
@Jokeswar could you please update this :+1:

**Comment by Jokeswar** [comment]
Implemented trough [bin/drone-config](https://github.com/vmck/acs-deploy/blob/master/bin/drone-config) and by [persistent config storage](https://github.com/vmck/acs-deploy/blob/master/nomad_jobs/drone.hcl#L18)
